In [7]:
%load_ext rpy2.ipython

In [8]:
%R R.Version()

<rpy2.robjects.vectors.ListVector object at 0x7f646ac84370> [RTYPES.VECSXP]
R classes: ('list',)
[StrSexpVe..., StrSexpVe..., StrSexpVe..., StrSexpVe..., ..., StrSexpVe..., StrSexpVe..., StrSexpVe..., StrSexpVe...]
  platform: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x7f64606d8140> [RTYPES.STRSXP]
R classes: ('character',)
['x86_64-pc-linux-gnu']
  arch: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x7f646070f410> [RTYPES.STRSXP]
R classes: ('character',)
['x86_64']
  os: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x7f6460719c30> [RTYPES.STRSXP]
R classes: ('character',)
['linux-gnu']
  system: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x7f6460719b90> [RTYPES.STRSXP]
R classes: ('character',)
['x86_64, linux-gnu']
...
  major: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x7f6460719050> [RTYPES.STRSXP]
R classes: ('character',)
['80002']
  minor: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x7f6460746820> [RTYPES.STRSXP]
R classes: ('character',)
['R']
  year: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x7f64607468c0> [RTYPES.STRSXP]
R classes: ('character',)
['R version 4.0.4 (2021-02-15)']
  month: <class 'rpy2.robjects.vectors.StrVector'>
  <rpy2.robjects.vectors.StrVector object at 0x7f64607467d0> [RTYPES.STRSXP]
R classes: ('character',)
['Lost Library Book']

In [9]:
%R install.packages("vctrs")

R[write to console]: Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

R[write to console]: trying URL 'https://cran.rstudio.com/src/contrib/vctrs_0.3.6.tar.gz'

R[write to console]: Content type 'application/x-gzip'
R[write to console]:  length 778016 bytes (759 KB)

R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write to console]: =
R[write 

In [10]:
%R a<-rnorm(20)

array([-0.4984016 ,  0.83366693, -0.19827633,  0.65775652, -1.62107658,
        0.39453297,  0.50709587,  0.62109276, -2.55916908,  0.70113119,
       -0.34950894,  0.21286597,  1.03690083,  0.54642211, -0.34826612,
        0.75632286, -0.07613707,  0.49897951, -0.14780656,  0.7123868 ])

In [11]:
%R b <- rep(NA, 20)
%R b
%R class(b)

<rpy2.robjects.vectors.StrVector object at 0x7f64606e9af0> [RTYPES.STRSXP]
R classes: ('character',)
['logical']

In [12]:
%R x <- c(a,b)

array([-0.4984016 ,  0.83366693, -0.19827633,  0.65775652, -1.62107658,
        0.39453297,  0.50709587,  0.62109276, -2.55916908,  0.70113119,
       -0.34950894,  0.21286597,  1.03690083,  0.54642211, -0.34826612,
        0.75632286, -0.07613707,  0.49897951, -0.14780656,  0.7123868 ,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan])

In [13]:
%R x <- sample(x, 20 , replace= FALSE)
%R x

array([        nan,         nan, -0.4984016 ,  0.62109276, -0.19827633,
        0.39453297,         nan,         nan, -2.55916908,  0.7123868 ,
               nan,         nan,         nan,         nan,         nan,
        0.54642211,         nan,         nan,  1.03690083,  0.83366693])

In [20]:
%R y<-x[10:15]
%R y

array([0.7123868,       nan,       nan,       nan,       nan,       nan])

In [21]:
%R sum(is.na(x))

array([11], dtype=int32)

In [22]:
%R sum(is.na(y))

array([5], dtype=int32)